src/Entity/Film.php
<?php

namespace App\Entity;

use App\Repository\FilmRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FilmRepository::class)
 */
class Film
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255  )
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $resume;

    /**
     * @ORM\Column(type="integer")
     */
    private $annee_sortie;

    /**
     * @ORM\ManyToOne(targetEntity=Genre::class, inversedBy="films")
     */
    private $genre;

    /**
     * @ORM\ManyToMany(targetEntity=Acteur::class, inversedBy="films")
     */
    private $acteurs;

    public function __construct()
    {
        $this->acteurs = new ArrayCollection();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }
   
    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getResume(): ?string
    {
        return $this->resume;
    }

    public function setResume(string $resume): self
    {
        $this->resume = $resume;

        return $this;
    }

    public function getAnneeSortie(): ?int
    {
        return $this->annee_sortie;
    }

    public function setAnneeSortie(int $annee_sortie): self
    {
        $this->annee_sortie = $annee_sortie;

        return $this;
    }

    public function getGenre(): ?Genre
    {
        return $this->genre;
    }

    public function setGenre(?Genre $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    /**
     * @return Collection|Acteur[]
     */
    

    public function addActeur(Acteur $acteur): self
    {
        if (!$this->acteurs->contains($acteur)) {
            $this->acteurs[] = $acteur;
        }

        return $this;
    }

    public function removeActeur(Acteur $acteur): self
    {
        $this->acteurs->removeElement($acteur);

        return $this;
    }

    public function getActeurs(): Collection
    {
        return $this->acteurs;
    }

    
    
}

src/Controller/FilmsController.php
<?php

namespace App\Controller;

use App\Entity\Acteur;
use App\Entity\Film;
use App\Entity\Genre;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\All;

class FilmsController extends AbstractController
{
    /**
     * @Route("/films", name="films")
     */
    public function index(): Response
    {
        $films = $this->getDoctrine()
            ->getRepository(Film::class)
            ->findAll();

        return $this->render('films/index.html.twig', [
            'controller_name' => 'FilmsController',
            'films'           => $films
        ]);
    }

    /**
     * @Route("/films/creer", name="films_create")
     */
    public function create(Request $request): Response
    {   

        if($request->isMethod("POST")){
            
            $titre = $request->request->get("titre");
            $resume = $request->request->get("resume");
            $annee_sortie = $request->request->get("annee_sortie");

            $genre_id = $request->request->get("genre");
            $genre = $this->getDoctrine()
                ->getRepository(Genre::class)
                ->find($genre_id);

            
            $acteur_id = $request->request->get("acteur");
            $acteur = $this->getDoctrine()
                ->getRepository(Acteur::class)
                ->find($acteur_id);
    

            $films = new Film;
            $films->setTitre($titre);
            $films->setResume($resume);
            $films->setAnneeSortie($annee_sortie);
            $films->setGenre($genre);
            $films->addActeur($acteur);
            
            
            

            $em = $this->getDoctrine()->getManager();
            $em->persist($films);
            $em->flush();
        
            return $this->redirectToRoute('films');
        
        }

       
            $acteurs = $this->getDoctrine()
            ->getRepository(Acteur::class)
            ->findAll();

            


            $genres = $this->getDoctrine()
                ->getRepository(Genre::class)
                ->findAll();


            return $this->render('films/create.html.twig', [
                'controller_name' => 'FilmsController',
                'genres' => $genres ,
                'acteurs' => $acteurs
           ]);
            

            }  

            
             /**
     * @Route("/films/{id}/edition", name="films_edit")
     */
    public function edit($id, Request $request ): Response
    {   


        $film = $this->getDoctrine()
            ->getRepository(Film::class)
            ->find($id);


        if($request->isMethod("POST")){
            $titre = $request->request->get("titre");
            $film->setTitre($titre);
            
            
            $em = $this->getDoctrine()->getManager();
            $em->flush();
        
            return $this->redirectToRoute('films');
        
        } 
            return $this->render('films/edit.html.twig', [
                'controller_name' => 'ActeursController',
                'film' => $film,
           ]);
        
        
         


            
            

            } 
             /**
            * @Route("/films/{id}/supression", name="films_delete")
            */
            
           public function delete($id,Request $request): Response
           {  
               
                   $film = $this->getDoctrine()
                       ->getRepository(Film::class)
                       ->find($id);
       
       
                   $em = $this->getDoctrine()->getManager();
                   $em->remove($film);
                   $em->flush();
               
                   return $this->redirectToRoute('films');
               
               
       
           }

        

}

templates/films/create.html.twig
<form method="POST">

    <p>
        <label for="titre">
            Titre
        </label>
        <input type="text" name="titre" id="titre" />
    </p>
    <p>
        <label for="resume">
            Résumé
        </label>
        <textarea name="resume" id="resume"></textarea>
    </p>
    <p>
        <label for="annee_sortie">
           Année de sortie
        </label>
        <input type="number" min="1900" max="2021" Step="1" name="annee_sortie" id="annee_sortie"></input>
    </p>

<p>
        <label for="acteur">
           acteur
        </label>
        <select  name="acteur"  id="acteur" multiple>
        {% for acteur in acteurs %}
                <option value="{{ acteur.id}}">{{ acteur.nom}}</option>
        {% endfor %}
        </select>
    </p>


    <p>
        <label for="genre">
           Genre
        </label>
        <select  name="genre"  id="genre" >
        {% for genre in genres %}
         <option value="{{ genre.id}}">{{ genre.nom}}</option>
        {% endfor %}
        </select>
    </p>
    

        <button type="submit">
            Enregistrer
        </buttom>
    </p>
</form>

templates/films/edit.html.twig
<form method="POST">

    <p>
        <label for="titre">
            titre
        </label>
        <input type="text" name="titre" id="titre" value="{{film.titre}}" />
    </p>


    <p>
        <button type="submit">
            Enregistrer
        </buttom>
    </p>
</form>

templates/films/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des {% endblock %}

{% block body %}

<a href="{{ url('films_create') }}">Nouveau Film</a>

<div>
    {% for film in films %}
        <h2>#{{ film.id }} : {{ film.titre }}</h2>
        <h3>Sortie : {{ film.anneeSortie }}</h3>

        <ul>
        {% for acteur in film.acteurs %}
        <li>{{acteur.nom}} {{acteur.prenom}}</li>
        {% endfor %}  
        </ul>

        
        <a href="{{ url('films_edit', { 'id':film.id } ) }}">Editer</a>
        <br/>

        {% if film.genre|length == 0 %}
        
        <a href="{{ url('films_delete', { 'id':film.id } ) }}">Supprimer</a>
        {% endif %}
        
        {% if film.genre is not null %}
        <h3>Genre : {{ film.genre.nom }}</h3>
        {% endif %}
        
        <p>{{film.resume}}</p>



        <hr />
    {% endfor %}   
</div>

{% endblock %}